config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "films#index"

  resources :films do
    collection do
      get "showing", to: "films#showing", as: :showing_films
      get "search", to: "films#search", as: :search_films
    end
    resources :comments
    resources :likes, only: [:create, :destroy]
  end
  resources :users, only: [:show, :edit, :update] do
    get 'like_films', on: :member
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cast.rb
class Cast < ApplicationRecord
  has_many :film_casts, dependent: :destroy
  has_many :films, through: :film_casts
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :film

  validates :comment, presence: true
end

app/models/film.rb
class Film < ApplicationRecord
  has_many :film_casts, dependent: :destroy
  has_many :casts, through: :film_casts
  has_many :film_trailers, dependent: :destroy
  has_many :trailers, through: :film_trailers
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :likers, through: :likes, source: :user

  def liked_by?(user)
    likes.where(user_id: user.id).exists?
  end

  validates :title, presence: true, uniqueness: true
end

app/models/film_cast.rb
class FilmCast < ApplicationRecord
  belongs_to :film
  belongs_to :cast
end

app/models/film_trailer.rb
class FilmTrailer < ApplicationRecord
  belongs_to :film
  belongs_to :trailer
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :film

  validates :user_id, presence: true
  validates :film_id, presence: true
end

app/models/trailer.rb
class Trailer < ApplicationRecord
  has_many :film_trailers, dependent: :destroy
  has_many :films, through: :film_trailers
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :nickname, presence: true

  has_many :comments
  has_many :likes, dependent: :destroy
  has_many :like_films, through: :likes, source: :film

  def self.authenticate(email, password)
    user = find_by(email: email)
    return user if user&.valid_password?(password)
    nil
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV['BASIC_AUTH_USER'] && password == ENV['BASIC_AUTH_PASSWORD']
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end

  def after_sign_in_path_for(resource)
    root_path
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_film
  before_action :set_comment, only: [:edit, :update, :destroy]

  def index
    @comments = @film.comments.includes(:user).order(created_at: :desc).page(params[:page]).per(5)
  end

  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.create(comment_params)
    @comment.user = current_user
    if @comment.save
      redirect_to film_path(@film)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @comment.update(comment_params)
      redirect_to user_path(@comment.user)
    else
      render :edit
    end
  end

  def destroy
    @comment.destroy
    redirect_to user_path(@comment.user)
  end

  private
  def find_film
    @film = Film.find(params[:film_id])
  end

  def comment_params
    params.require(:comment).permit(:comment).merge(user_id: current_user.id, film_id: params[:film_id])
  end

  def set_comment
    @comment = @film.comments.find(params[:id])
  end
end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
  require 'romaji'
  before_action :set_q, only: [:index, :search]

  def index
    @films = if params[:q].present? || search_params_present?
               FilmSearchQuery.new(params).call.page(params[:page]).per(10)
             else
               Film.all.page(params[:page]).per(10)
             end
  end

  def showing
    @films = Film.order(release_date: :desc).page(params[:page]).per(10)
  end

  def search
    @films = FilmSearchQuery.new(params).call.page(params[:page]).per(10)
  end

  def show
    @film = Film.find(params[:id])
    @casts = @film.casts
    @trailers = @film.trailers
  end

  private

  def set_q
    @q = Film.ransack(params[:q])
  end

  def search_params_present?
    params.values_at(:search_title, :search_cast, :search_staff).any?(&:present?)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_film, only: [:create, :destroy]

  def create
    current_user.likes.create(film: @film)
    render partial: 'likes/like', locals: { film: @film }
  end

  def destroy
    current_user.likes.find_by(film: @film)&.destroy
    if params[:referer] == 'my_page'
      render turbo_stream: turbo_stream.remove(helpers.dom_id(@film, :like))
    else
      redirect_to request.referer || root_path
    end
  end

  private

  def set_film
    @film = Film.find(params[:film_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def show
    @user = current_user
    @comments = @user.comments.includes(:film)
    @likes = @user.likes.includes(:film)
  end

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to user(@user)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:nickname, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/edit.html.erb
<%= render "shared/navbar" %>
<div class="new-main">
  <div class="comment-left"></div>
  <div class="new-content">
    <div class="new-items">
      <h1 class="new-title"><%= @film.title %></h1>
      <%= form_with(model: [@film, @comment], local: true) do |f| %>
        <div class="comment-field">
          <%= image_tag "commentbar.png", class: "commentbar" %>
          <%= f.label :comment, "編集", class: "review-label" %>
          <%= f.text_area :comment, autofocus: true, class: "review-text" %>
          <%= image_tag "commentbar.png", class: "commentbar" %>
        </div>
        <div class="edit-comment-actions">
          <%= f.submit "ホリック", class:"edit-button" %>
          <%= link_to "Back", user_path(@comment.user), class: "comment-edit-back" %>
          <%= link_to "Delete", film_comment_path(@film, @comment), data: { turbo_method: :delete }, class: "delete-button" %>
        </div>
      <% end %>
    </div>
  </div>
  <div class="comment-right"></div>
</div>

app/views/comments/index.html.erb
<%= render "shared/navbar" %>
<div class="comment-main">
  <div class="filmline-left"></div>
  <div class="comment-content">
    <div class="comment-top">
      <h1 class="film-title"><%= @film.title %></h1>
      <%= link_to 'Back', film_path(@film), class: "back-link" %>
    </div>
    <h1 class="review">レビュー</h1>
    <div class="comment-bottom">
      <div class="comment-items">
        <% @comments.each do |comment| %>
          <div class="comment-item">
            <div class="comment-text"><%= comment.comment %></div>
            <div class="comment-user"><%= comment.user.nickname %></div>
          </div>
        <% end %>
      </div>
    </div>
    <%= paginate @comments %>
  </div>
  <div class="filmline-right"></div>
</div>

app/views/comments/new.html.erb
<%= render "shared/navbar" %>
<div class="new-main">
  <div class="comment-left"></div>
  <div class="new-content">
    <div class="new-items">
      <h1 class="new-title"><%= @film.title %></h1>
      <%= form_with(model: [@film, @comment], local: true) do |f| %>
        <div class="comment-field">
          <%= image_tag "commentbar.png", class: "commentbar" %>
          <%= f.label :comment, "レビュー", class: "review-label" %>
          <%= f.text_area :comment, autofocus: true, class: "review-text" %>
          <%= image_tag "commentbar.png", class: "commentbar" %>
        </div>
        <div class="comment-actions">
          <%= f.submit "ホリック", class:"post-button" %>
          <%= link_to "Back", film_path(@film), class: "comment-back" %>
        </div>
      <% end %>
    </div>
  </div>
  <div class="comment-right"></div>
</div>

app/views/films/_film.html.erb
<%= link_to film_path(film), class: "film", data: {turbo: false} do %>
  <div class="left-show">
    <% if film.poster_image_url.present? && film.poster_image_url != "/global/images/jfdb_noimage.png" %>
      <%= image_tag(film.poster_image_url, class: "index-poster-image") %>
    <% else %>
      <%= image_tag(asset_path('noimage.png'), class: "index-poster-image noimage") %>
    <% end %>
  </div>
  <div class="right-show">
    <div class="title-show">
      <h2><%= film.title %></h2>
      <div class="release-date"><%= film.release_date %></div>
    </div>
    <div class="text-show">
      <p><%= film.description %></p>
    </div>
  </div>
<% end %>

app/views/films/index.html.erb
<%= render "shared/navbar" %>
<div class="index-main">
  <div class="curtain">
    <%= image_tag "curtain.jpg", class: "curtain-image" %>
    <video id="opening-video" data: {turbo: false} autoplay muted class="open-video"
           data-webm="<%= asset_path('opennuke.webm') %>"
           data-mp4="<%= asset_path('opennuke.mp4') %>">
      Your browser does not support the video tag.
    </video>
    <div class="contents">
      <%= form_with(url: search_films_films_path, method: "get", local: true, class: "main-search-form") do |form| %>
        <div class="top-content">
          <label>
            <%= form.check_box :search_title, {}, "1", "0" %>
            <span class="checkbox-label">タイトル</span>
          </label>
          <label>
            <%= form.check_box :search_cast, {}, "1", "0" %>
            <span class="checkbox-label">俳優名</span>
          </label>
          <label>
            <%= form.check_box :search_staff, {}, "1", "0" %>
            <span class="checkbox-label">スタッフ</span>
          </label>
        </div>
        <div class="search-container">
        <%= form.text_field :q_cont, placeholder: "Search", class: "search-input" %>
        <%= form.submit "ホリック", class: "search-btn" %>
        </div>
      <% end %>
      <div class="bottom-content">
        <%= link_to "上映中", showing_films_films_path, class: "enter-buttin" %>
      </div>
    </div>
  </div>
</div>

app/views/films/search.html.erb
<%= render "shared/navbar" %>
<div class="film-main">
  <div class="filmline-left"></div>
  <div class="content">
  <% if @films.present? %>
    <div class="shows">
      <% @films.each do |film| %>
        <%= render partial: "film", locals: { film: film } %>
      <% end %>
    </div>
    <div class="pagination-desktop">
      <%= paginate @films %>
    </div>
    <div class="pagination-tablet">
      <%= paginate @films, window: 2 %>
    </div>
    <div class="pagination-mobile">
      <%= paginate @films, window: 1 %>
    </div>
  <% else %>
    <p><%= flash.now[:alert] || "映画が見つかりませんでした。" %></p>
  <% end %>
  </div>
  <div class="filmline-right"></div>
</div>

app/views/films/show.html.erb
<%= render "shared/navbar" %>
<div class="film-main">
  <div class="filmline-left"></div>
  <div class="content">
    <div class="shows">
      <div class="show-detail">
        <div class="show-top">
          <div class="left-show-top">
            <%= image_tag(@film.poster_image_url.present? && @film.poster_image_url != "/global/images/jfdb_noimage.png" ? @film.poster_image_url : asset_path('noimage.png'), class: "show-poster-image") %>
          </div>
          <div class="right-show-top">
            <div class="right-top">
              <small class="show-date">( <%= @film.release_date %> )</small>
              <h2><%= @film.title %></h2>
            </div>
            <div class="right-bottom">
              <div class="comment-link"><%= link_to "レビュー", film_comments_path(@film) %></div>
              <div class="comment-link"><%= link_to "投稿", new_film_comment_path(@film) %></div>
              <div id="like-btn<% @film.id %>">
                <% if user_signed_in? %>
                  <%= render partial: "likes/like", locals: { film: @film } %>
                <% else %>
                  <%= link_to image_tag("unlike.png", class: "like-icon"), new_user_session_path, class: "film_likes" %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
        <div class="film-detail">
          <div class="text-selection">
            <% @trailers.each do |trailer| %>
              <p><%= trailer.text %></p>
            <% end %>
          </div>
          <div class="cast-and-staff">
            <div class="cast-section">
            <h3>キャスト</h3>
              <ul>
                <% @casts.each do |cast| %>
                  <li><%= cast.name %></li>
                <% end %>
              </ul>
            </div>
            <div class="staff-section">
            <h3>スタッフ</h3>
              <ul>
                <% @trailers.each do |trailer| %>
                  <% if trailer.role.present? && trailer.name.present? %>
                    <li><strong><%= trailer.role %> : </strong> <%= trailer.name %></li>
                  <% elsif trailer.role.present? %>
                    <li><strong><%= trailer.role %></strong></li>
                  <% elsif trailer.name.present? %>
                    <li><%= trailer.name %></li>
                  <% end %>
                <% end %>
              </ul>
            </div>
          </div>
          <div class="production-section">
            <% @trailers.each do |trailer| %>
              <% if trailer.production.present? %>
                <div class="production-name">
                  <p><strong>制作会社 :</strong> <%= trailer.production %></p>
                </div>
              <% end %>
              <% if trailer.official_site.present? %>
                <div class="site">
                  <p><strong>公式サイト :</strong> <%= link_to trailer.official_site, trailer.official_site %></p>
                </div>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="filmline-right"></div>
</div>

app/views/films/showing.html.erb
<%= render "shared/navbar" %>
<div class="film-main">
  <div class="filmline-left"></div>
  <div class="content">
    <div class="shows">
      <% @films.each do |film| %>
        <%= render partial: "film", locals: { film: film } %>
      <% end %>
    </div>
    <div class="pagination-desktop">
      <%= paginate @films %>
    </div>
    <div class="pagination-tablet">
      <%= paginate @films, window: 2 %>
    </div>
    <div class="pagination-mobile">
      <%= paginate @films, window: 1 %>
    </div>
  </div>
  <div class="filmline-right"></div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CINEHOLIC</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="csrf-token" content="<%= form_authenticity_token %>">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Hina+Mincho&display=swap" rel="stylesheet" type="text/css">
    <link rel="preload" href="<%= asset_path('application.css') %>" as="style">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/likes/_like.html.erb
<%= turbo_frame_tag dom_id(film, :like) do %>
  <% if film.liked_by?(current_user) %>
    <% like = film.likes.find_by(user: current_user) %>
    <%= link_to image_tag("like.png", class: "like-icon"), film_like_path(film.id, like.id), data: { turbo_method: :delete, turbo_frame: dom_id(film, :like) }, class: "film_likes" %>
  <% else %>
    <%= link_to image_tag("unlike.png", class: "like-icon"), film_likes_path(film.id), data: { turbo_method: :post, turbo_frame: dom_id(film, :like) }, class: "film_likes" %>
  <% end %>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar">
  <div class="logo"><%= link_to image_tag("title.png", class:"title-icon"), "/" %></div>
  <div class="menu" id="menu">
    <span><%= image_tag "menu.png" %></span>
    <ul class="lists hidden" id="pull-down">
      <li class="top-list"><%= link_to "上映作品", showing_films_films_path %></li>
      <% if user_signed_in? %>
      <li class="second-list"><%= link_to "マイページ", user_path(current_user) %></li>
      <li class="third-list"><%= link_to "ログアウト", destroy_user_session_path, data: { turbo_method: :delete }%></li>
      <% else %>
      <li class="fourth-list"><%= link_to "サインイン", new_user_registration_path %></li>
      <li class="fifth-list"><%= link_to "ログイン", new_user_session_path %></li>
      <% end %>
      <li class="dropdown">
        <div class="dropdown-content">
          <%= form_tag(search_films_films_path, method: "get", class: "search-form") do %>
            <input type="text" name="q" placeholder="Search" style="text-align: right;">
            <button type="submit">GO</button>
          <% end %>
        </div>
      </li>
    </ul>
  </div>
</div>

app/views/users/_like.html.erb
<div class="my-like-button">
  <% if user_signed_in? && film.liked_by?(current_user) %>
    <% like = film.likes.find_by(user: current_user) %>
    <%= link_to image_tag("like.png", class: "like-icon"), film_like_path(film.id, like.id, referer: 'my_page'), data: { turbo_method: :delete, turbo_frame: dom_id(film, :like) }, class: "film_likes" %>
  <% else %>
    <%= link_to image_tag("unlike.png", class: "like-icon"), film_likes_path(film.id), data: { turbo_method: :post, turbo_frame: dom_id(film, :like) }, class: "film_likes" %>
  <% end %>
</div>

app/views/users/_show.html.erb
<div class="my-comment">
  <div class="my-comment-area">
    <div class="top-my-comment-area">
      <div class="my-comment-film">
        <%= link_to comment.film.title, film_path(comment.film) %> 
      </div>
      <a href="<%= edit_film_comment_path(comment.film, comment) %>" class="comment-icon-link">
        <%= image_tag "icon.png", size: '30x30', class: "comment-icon" %>
        <div class="comment-icon-overlay"></div>
      </a>
      </div>
    <div class="my-comment-text">
      <%= comment.comment %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="account-page">
  <div class="container">
    <h2>アカウントの編集</h2>
    <%= form_with model: current_user, local: true do |f|%>
      <%= render "devise/shared/error_messages", resource: current_user %>

      <div class='user-field'>
        <%= f.label :nickname%><br />
        <%= f.text_field :nickname, autofocus: true%>
      </div>

      <div class="user-field">
        <%= f.label :email %><br />
        <%= f.email_field :email %>
      </div>

      <div class='user-actions'>
        <%= f.submit "Update", class: 'btn'%>
        <%= link_to "Back", user_path(current_user) %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<%= render "shared/navbar" %>
<div class="my-main">

  <div class="my-left-page">
    <div class="my-left-items">
      <div class="my-left-top">
        <div class="my-name">
          <%= @user.nickname %>
        </div>
        <div class="my-edit">
          <a href="<%= edit_user_path(@user) %>" class="edit-icon-link">
            <%= image_tag "icon.png", size: '50x50', class: "edit-icon" %>
            <div class="edit-icon-overlay"></div>
          </a>
        </div>
      </div>
      <div class="my-left-bottom">
        <div class="like-head">お気に入り</div>
        <div class="my-like-lists">
          <% @likes.each do |like| %>
            <% film = like.film %>
            <%= turbo_frame_tag dom_id(film, :like) do %>
              <div class="my-like-film" id="film_<%= film.id %>">
                <%= render partial: "like", locals: { film: film } %>
                <%= link_to film_path(film), data: { turbo: false } do %>
                  <div class="my-title">
                    <%= film.title %>
                  </div>
                <% end %>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="my-left-line"></div>
  </div>

  <div class="my-right-page">
    <div class="my-right-items">
      <div class="my-record">
        <h1 class="record">Record</h1>
        <div class="my-comments">
          <% @comments.each do |comment| %>
            <%= render partial: "show", locals: { comment: comment } %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="my-right-line"></div>
  </div>
</div>